---
galaxy_info:
  author: Yannick Sébastia
  description: Install the OpenShift CLI (oc) and openshift-install binaries
  company: Zenika
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  galaxy_tags: []
dependencies: []
