---
# tasks file for vagrant_ansible_node
- name: Controller - get ssh key # noqa: run-once[task]
  ansible.builtin.slurp:
    src: "{{ vagrant_ansible_node_ssh_key }}.pub"
  register: vagrant_ansible_node_ssh_pub_key
  run_once: true
  delegate_to: "{{ vagrant_ansible_node_controller }}"
- name: Nodes - create remote group
  become: true
  ansible.builtin.group:
    name: "{{ vagrant_ansible_node_lab_group }}"
    state: present
- name: Nodes - create remote user
  become: true
  ansible.builtin.user:
    name: "{{ vagrant_ansible_node_lab_user }}"
    group: "{{ vagrant_ansible_node_lab_group }}"
    shell: /bin/bash
    state: present
- name: Nodes - create sudo file
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/lab
    mode: "0644"
    content: |
      %{{ vagrant_ansible_node_lab_group }} ALL=(ALL) NOPASSWD:ALL
- name: Nodes - push controller SSH key
  become: true
  ansible.posix.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ vagrant_ansible_node_ssh_pub_key['content'] | b64decode }}"
  loop:
    - "{{ vagrant_ansible_node_lab_user }}"
