---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: zenika
name: training
version: 0.1.0
readme: README.md
authors:
  - Yannick Sébastia (github.com/ysebastia)
description: Collection Ansible associée à la génération des labs de formation
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - linux
dependencies:
  "ansible.posix": ">=2.0.0"
  "community.crypto": ">=2.26.1"
repository: https://github.com/Zenika-Training/ansible_collection
homepage: https://github.com/Zenika-Training/ansible_collection
issues: https://github.com/Zenika-Training/ansible_collection/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
