---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 2.9.0
  - name: awx.awx
    version: 24.6.1
  - name: community.crypto
    version: 3.0.1
  - name: containers.podman
    version: 1.16.4
  - name: kubernetes.core
    version: 6.0.0
