---
awx_admin: admin
awx_chart_version: 3.2.1
awx_config: "{{ ansible_facts.user_dir }}/.tower_cli.cfg"
awx_controller_port: 32000
awx_kube_config: "{{ ansible_facts.user_dir }}/.kube/config"
awx_helm: /usr/local/bin/helm
awx_name: awx
awx_ns: awx
awx_private_registry: local-registry
awx_workdir: "/tmp/awx"
