---
- name: Resolve kubeconfig path
  ansible.builtin.include_role:
    name: zenika.training.ocp_utils
    tasks_from: resolve_kubeconfig.yml
  vars:
    _kube_path: "{{ bind_dns_kubeconfig }}"

- name: Apply resolved kubeconfig
  ansible.builtin.set_fact:
    bind_dns_kubeconfig: "{{ ocp_utils_kubeconfig_resolved }}"
