---
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  yamllint:
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - run: echo yamllint > requirements.txt
      - python/install-packages:
          pkg-manager: pip
      - run: yamllint $(pwd)

  ansible-lint:
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - run: echo ansible-lint > requirements.txt
      - python/install-packages:
          pkg-manager: pip
      - run: ansible-galaxy collection install -r requirements.yml --collections-path "~/.ansible/collections"
      - run: ansible-lint --parseable $(pwd)

workflows:
  version: 2

  lint:
    jobs:
      - yamllint
      - ansible-lint
