---
- name: Converge
  hosts: all
  tasks:
    - name: "Include vagrant_ansible_controller"
      ansible.builtin.include_role:
        name: "zenika.training.vagrant_ansible_controller"
      vars:
        vagrant_ansible_controller_user: "{{ ansible_user_id }}"
