---
- name: Add a helm repository
  kubernetes.core.helm_repository:
    binary_path: "{{ awx_helm }}"
    kubeconfig: "{{ awx_kube_config }}"
    name: awx-operator
    repo_url: https://ansible-community.github.io/awx-operator-helm/
  vars:
    ansible_python_interpreter: "{{ awx_venv_path }}/ansible-core/bin/python"
- name: Install Helm diff plugin
  kubernetes.core.helm_plugin:
    binary_path: "{{ awx_helm }}"
    kubeconfig: "{{ awx_kube_config }}"
    plugin_path: https://github.com/databus23/helm-diff
    state: present
  vars:
    ansible_python_interpreter: "{{ awx_venv_path }}/ansible-core/bin/python"
- name: Deploy Awx operator
  kubernetes.core.helm:
    binary_path: "{{ awx_helm }}"
    chart_ref: awx-operator/awx-operator
    chart_version: "{{ awx_chart_version }}"
    context: kind-kind
    create_namespace: true
    kubeconfig: "{{ awx_kube_config }}"
    name: awx-operator
    release_namespace: "{{ awx_ns }}"
  vars:
    ansible_python_interpreter: "{{ awx_venv_path }}/ansible-core/bin/python"
  environment:
    no_proxy: 127.0.0.1
- name: Generate node port
  ansible.builtin.template:
    src: awx-cr.yaml.j2
    dest: "{{ awx_workdir }}/awx-cr.yaml"
    mode: "0644"
- name: Add node port
  kubernetes.core.k8s:
    context: kind-kind
    kubeconfig: "{{ awx_kube_config }}"
    namespace: "{{ awx_ns }}"
    src: "{{ awx_workdir }}/awx-cr.yaml"
    state: present
  vars:
    ansible_python_interpreter: "{{ awx_venv_path }}/ansible-core/bin/python"
- name: Wait install of AWX
  ansible.builtin.uri:
    url: "http://localhost:{{ awx_controller_port }}"
    return_content: true
    status_code: 200
    follow_redirects: "none"
  register: awx_uri_output
  until: awx_uri_output.status == 200
  retries: 120
  delay: 10
