---
- name: Configure system
  ansible.builtin.include_tasks: system.yml

- name: Install AWX
  ansible.builtin.include_tasks: install.yml

- name: Configure AWX
  ansible.builtin.include_tasks: configure.yml

- name: Awx authentification and information
  ansible.builtin.debug:
    msg:
      - "(0) AWX login: {{ awx_admin }}"
      - "(1) AWX password: {{ awx_password }}"
      - "(2) AWX url : http://{{ ansible_facts.default_ipv4.address }}:{{ awx_controller_port }}"
      - "(3) Registry url: http://{{ ansible_facts.default_ipv4.address }}:{{ awx_registry_local_port }}"
