---
- name: Start local private registry
  containers.podman.podman_container:
    name: "{{ awx_private_registry }}"
    image: docker.io/registry:2
    state: started
    publish:
      - "0.0.0.0:{{ awx_registry_local_port }}:5000"
