---
- name: Collect needed facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - effective_user_id
      - network
- name: Create workdir
  ansible.builtin.file:
    state: directory
    path: "{{ awx_workdir }}"
    mode: "0755"
