---
galaxy_info:
  author: Yannick Sébastia
  description: Configuration d'un controleur AWX
  company: Zenika

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: GPL-3.0-only

  min_ansible_version: "2.1"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies:
  - role: zenika.training.ansible_virtualenv
    vars:
      ansible_virtualenv_directory: "{{ awx_virtualenv_directory }}"
    when:
      - awx_enable_dependencies | default(true)
  - role: zenika.training.podman
    vars:
      podman_registry_local_port: "{{ awx_registry_local_port }}"
    when:
      - awx_enable_dependencies | default(true)
