# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  
  config.nfs.functional = false
  
  # https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html
  config.vm.provider "libvirt" do |guest|
    guest.default_prefix = "collection_"
    guest.cpus = "4"
    guest.memory = "8128"
  end
  
  config.vm.define "ubuntu24" do |guest|
    guest.vm.box = "ubuntu24"
    guest.vm.hostname = "ubuntu24"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.groups = {
        "controller" => ["ubuntu24"],
    }      
    ansible.playbook = "provision.yml"
  end

end
