---
- name: Ansible global configuration
  when:
    - ansible_global_configuration_ansible_action in ['converge']
  block:
    - name: Include tasks
      ansible.builtin.include_tasks: "{{ ansible_global_configuration_ansible_action }}.yml"
