---
- name: Container - install packages
  become: true
  ansible.builtin.package:
    name:
      - containers-storage
      - fuse-overlayfs
      - podman
      - slirp4netns
      - tree
      - uidmap
    state: present
- name: Container - allow insecure registry
  become: true
  ansible.builtin.copy:
    mode: "0644"
    dest: /etc/containers/registries.conf.d/private.conf
    content: |
      [[registry]]
      location = "localhost:{{ podman_registry_local_port }}"
      insecure = true
# cf https://kind.sigs.k8s.io/docs/user/rootless/
- name: Container - create delegate requirements directory for rootless usage
  become: true
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/user@.service.d/
    mode: "0755"
- name: Container - configure requirements with Systemd
  become: true
  ansible.builtin.copy:
    mode: "0644"
    dest: /etc/systemd/system/user@.service.d/delegate.conf
    content: |
      [Service]
      Delegate=yes
  notify: Reload systemd
- name: Container - configure IPtables modules
  become: true
  ansible.builtin.copy:
    dest: /etc/modules-load.d/iptables.conf
    mode: "0644"
    content: |
      ip6_tables
      ip6table_nat
      ip_tables
      iptable_nat
- name: Container - configure containers limit
  become: true
  ansible.builtin.copy:
    dest: /etc/containers/containers.conf
    mode: "0644"
    content: |-
      [containers]
      pids_limit = 0
- name: Container - configure storage driver
  become: true
  ansible.builtin.copy:
    dest: /etc/containers/storage.conf
    mode: "0644"
    content: |-
      [storage]
      driver = "overlay"
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
