---
- name: Install needed packages
  become: true
  ansible.builtin.package:
    name: "{{ ansible_virtualenv_packages }}"

- name: Ensure that Ansible is installed
  community.general.pipx:
    name: "{{ list }}"
  loop: "{{ ansible_virtualenv_pip }}"
