---
- name: Facts
  ansible.builtin.include_tasks: "facts.yml"
- name: Emulate controller.sh script
  ansible.builtin.include_tasks: controller.yml
- name: Emulate materials-helper.sh script
  ansible.builtin.include_tasks: materials-helper.yml
- name: Emulate TP environment
  ansible.builtin.include_tasks: tp-environment.yml
