---
- name: Read kubeadmin password
  ansible.builtin.slurp:
    src: "{{ oc_coreos_work_dir }}/{{ oc_coreos_ocp_name }}/auth/kubeadmin-password"
  register: oc_coreos_kubeadmin_password

- name: ISO ready
  ansible.builtin.debug:
    msg:
      - "ISO        : {{ oc_coreos_work_dir }}/rhcos-live.iso"
      - "Node       : {{ oc_coreos_ocp_name }}.{{ oc_coreos_ocp_domain }}"
      - "Network    : {{ oc_coreos_ocp_network }}"
      - "kubeadmin  : {{ oc_coreos_kubeadmin_password.content | b64decode | trim }}"
