---
galaxy_info:
  author: Yannick Sébastia
  description: Préparation ISO RHCOS SNO (Single Node OpenShift) avec ignition embarqué
  company: Zenika
  license: GPL-3.0-only
  min_ansible_version: "2.1"
  galaxy_tags: []
dependencies: []
