---
- name: Get current OC client version
  ansible.builtin.command:
    cmd: /usr/local/bin/oc version --client -o json
  register: oc_command_version_result
  failed_when: false
  changed_when: false

- name: Set installed OC version to empty
  ansible.builtin.set_fact:
    oc_command_installed_version: ""

- name: Set installed OC version from running binary
  ansible.builtin.set_fact:
    oc_command_installed_version: "{{ (oc_command_version_result.stdout | from_json).releaseClientVersion | default('') }}"
  when: oc_command_version_result.rc == 0 and oc_command_version_result.stdout != ''

- name: Download OC command
  become: true
  ansible.builtin.unarchive:
    src: "{{ oc_command_repo }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  when: oc_command_installed_version != oc_command_version

- name: Bash completion for oc
  become: true
  ansible.builtin.shell:
    cmd: "(/usr/local/bin/oc completion bash) > /etc/profile.d/oc.sh"
    creates: /etc/profile.d/oc.sh
  when: oc_command_installed_version != oc_command_version
