---
- name: Configure AWX
  awx.awx.settings:
    controller_config_file: "{{ awx_provisioning_config }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ awx_provisioning_settings }}"
- name: Provisioning AWX
  ansible.builtin.include_tasks: provisioning.yml
  loop: "{{ awx_provisioning_iac }}"
  loop_control:
    loop_var: awx_item
  when:
    - awx_provisioning_iac is defined
    - awx_provisioning_iac | length > 0
