---
- name: "Manage roles for {{ team_assignment.team }}"
  awx.awx.role_team_assignment:
    team: "{{ team_assignment.team }}"
    role_definition: "{{ item }}"
    object_id: 1
    state: present
    controller_config_file: "{{ awx_provisioning_config }}"
  loop: "{{ team_assignment.role_definition }}"
  when:
    - team_assignment.role_definition is defined