---
- name: "Manage roles for {{ teams.name }}"
  awx.awx.role_team_assignment:
    team: "{{ teams.name }}"
    role_definition: "{{ item }}"
    object_id: "{{ awx_provisioning_organization.id }}"
    state: present
    controller_config_file: "{{ awx_provisioning_config }}"
  loop: "{{ teams.role_definition }}"
  when:
    - teams.role_definition is defined
