---
- name: "Manage members of {{ team_roles.team }}"
  awx.awx.role:
    users: "{{ item.name }}"
    target_teams: "{{ team_roles.team }}"
    role: "{{ item.role }}"
    state: present
    controller_config_file: "{{ awx_provisioning_config }}"
  loop: "{{ team_roles.members }}"
  when: team_roles.members is defined
- name: "Manage credentials of {{ team_roles.team }}"
  awx.awx.role:
    teams: "{{ team_roles.team }}"
    credentials: "{{ item.name }}"
    role: "{{ item.role }}"
    state: present
    controller_config_file: "{{ awx_provisioning_config }}"
  loop: "{{ team_roles.credentials }}"
  when: team_roles.credentials is defined
- name: "Manage projects of {{ team_roles.team }}"
  awx.awx.role:
    teams: "{{ team_roles.team }}"
    projects: "{{ item.name }}"
    role: "{{ item.role }}"
    state: present
    controller_config_file: "{{ awx_provisioning_config }}"
  loop: "{{ team_roles.projects }}"
  when: team_roles.projects is defined
- name: "Manage inventories of {{ team_roles.team }}"
  awx.awx.role:
    teams: "{{ team_roles.team }}"
    inventories: "{{ item.name }}"
    role: "{{ item.role }}"
    state: present
    controller_config_file: "{{ awx_provisioning_config }}"
  loop: "{{ team_roles.inventories }}"
  when: team_roles.inventories is defined
- name: "Manage jobs of {{ team_roles.team }}"
  awx.awx.role:
    teams: "{{ team_roles.team }}"
    job_templates: "{{ item.name }}"
    role: "{{ item.role }}"
    state: present
    controller_config_file: "{{ awx_provisioning_config }}"
  loop: "{{ team_roles.job_templates }}"
  when: team_roles.job_templates is defined
- name: "Manage Workflows of {{ team_roles.team }}"
  awx.awx.role:
    teams: "{{ team_roles.team }}"
    workflows: "{{ item.name }}"
    role: "{{ item.role }}"
    state: present
    controller_config_file: "{{ awx_provisioning_config }}"
  loop: "{{ team_roles.workflows }}"
  when: team_roles.workflows is defined
