---
prerun: false
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        ansible_user: ansible
driver:
  name: podman
platforms:
  - name: "ubuntu${CI_COMMIT_SHORT_SHA}"
    image: docker.io/ysebastia/molecule:jammy
    pre_build_image: true
    env:
      HTTPS_PROXY: "${HTTPS_PROXY}"
      HTTP_PROXY: "${HTTPS_PROXY}"
    stop_signal: "SIGRTMIN+3"
    security_opts:
      - "label=disable"
    capabilities:
      - CAP_MKNOD
      - CAP_NET_ADMIN
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
      - CAP_SYS_ADMIN
    command: "/usr/sbin/init"
    tmpfs: { "/tmp": "exec", "/var/tmp": "exec", "/run": "rw,noexec,nosuid,nodev" }
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host
    network: molecule
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
