---
galaxy_info:
  author: zenika
  description: Rôle d'évaluation de la progression des TPs de formation
  company: Zenika
  license: GPL-3.0-only
  min_ansible_version: "2.1"
  galaxy_tags: []
dependencies: []
