---
galaxy_info:
  author: zenika
  description: Declarative lab grading role for Zenika training courses
  company: Zenika
  license: GPL-3.0-only
  min_ansible_version: "2.1"
  galaxy_tags: []
dependencies: []
