---
- name: Day-1 OpenShift cluster configuration
  hosts: "{{ ansible_limit | default('sno') }}"
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: Configure authentication and RBAC
      ansible.builtin.include_role:
        name: zenika.training.ocp_init

    - name: Bootstrap shared PKI and deploy cert-manager CA secret
      ansible.builtin.include_role:
        name: zenika.training.ocp_pki

    - name: Install MetalLB
      ansible.builtin.include_role:
        name: zenika.training.metallb
      when: metallb_ip_ranges is defined and metallb_ip_ranges | length > 0

    - name: Deploy BIND9 DNS server
      ansible.builtin.include_role:
        name: zenika.training.bind_dns
      when: bind_dns_zone_name is defined and bind_dns_zone_name | length > 0
        and bind_dns_lb_ip is defined and bind_dns_lb_ip | length > 0
